#!/bin/bash
read -p "Setup Apache and users from csv file? y/n" -n 1 -r
	
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		./setup_apache
		# move the config files.
		mv config_files/* /etc/apache2/sites-available/
		# run users script and delete it
		chmod o+x scripts/users
		./scripts/users
		echo "Deleting users scripts for security. \n"
		rm scripts/users
	fi
