#!/usr/bin/php

<?php
function ask($prompt) {
	echo $prompt . " :";
	return fopen ("php://stdin","r");
}

function answer($answer, $true) {
	$line = fgets($answer);
	
	if(trim($line) == $true){
    	return true;
    }
}

function line($val) {
	echo $val."/n";
}

function read_csv($filename = "data.csv") {
	return array_map('str_getcsv', file($filename));
}

//$q = ask("Am I a question? y/n");
//$reply = (answer($q, "y") ? "true" : "false");
//line($reply);
line("Reading CSV file");
$csv = read_csv();
$fields = array_shift($csv);

line("Reading templates");
$apache_template = file_get_contents("templates/wp_vhosts_template.tmpl");
$bash_template = file_get_contents("templates/bash-setup.tmpl");

foreach ($fields as $key => $value) {
	$fields[$key] = "{{".strtoupper($value)."}}";
}
	
	if(!file_exists("config_files")) mkdir("config_files");
	if(!file_exists("scripts")) mkdir("scripts");
	
line("Writing Files ...");

foreach ($csv as $ckey => $cvalue) {
	$apache = str_replace($fields, $csv[$ckey], $apache_template);
	line("Creating " . "config_files/" . $csv[$ckey][0] . ".conf");
	file_put_contents("config_files/" . $csv[$ckey][0] . ".conf", $apache);
	
	$bash = str_replace($fields, $csv[$ckey], $bash_template);
	line("Appending command to scripts/users");
	file_put_contents("scripts/users", "\n".$bash, FILE_APPEND);
}