#!/usr/bin/php

<?php
function ask($prompt) {
	echo $prompt . " :";
	return fopen ("php://stdin","r");
}

function answer($answer, $true) {
	$line = fgets($answer);
	
	if(trim($line) == $true){
    	return true;
    }
}

function line($val) {
	echo $val."/n";
}

function read_csv($filename = "data.csv") {
	return array_map('str_getcsv', file($filename));
}

//$q = ask("Am I a question? y/n");
//$reply = (answer($q, "y") ? "true" : "false");
//line($reply);

$csv = read_csv();
$fields = array_shift($csv);

$template = file_get_contents("templates/wp_vhosts_template.tmpl");

foreach ($fields as $key => $value) {
	$fields[$key] = "{{".strtoupper($value)."}}";
}

$result = str_replace($fields, $csv[1], $template);

print_r($template);